### ISSUE TITLE
Namespacing philosophy

### ISSUE THREAD

**Issue by helins** [Convex-Dev/design#1]
A rationale for what namespacing is and how it behaves has yet to be built.

Currently:

- Keywords are not namespaced and might never be (but Convex-Dev/convex#57 must be fixed to reflect that)
- Symbols are namespaced but the namespace is not accessible through Lisp (ie. there is a `name`  function but no `namespace`)

On Discord, @mikera was hinting that symbols could have more than 2 segments and segments could be something else than symbols. For instance, leading with an address:

```clojure
#42/some/prop
```

Points to consider:

1. Some namespacing must exist, at least 2 segments since library imports rely on this.
2. Not namespacing keywords is fine but:
2.1. Does it help making a distinction between symbols and keywords? (confusing point for non-Clojurist)
2.2. Doesn't it look like keywords are mere enums?
3. Are symbols > 2 segments really needed?
3.1. How are segments extracted (as opposed to using `namespace` and `name`)?
3.2. Isn't it better to use an arbitrary vector?
3.3. Or nested maps, depending on usecase?

**Comment by violattice** [comment]
matrix://control.system/jail-box/atomized-entity

**Comment by helins** [comment]
?

**Comment by mikera** [comment]
I believe we have settled on the right solution for this. Lookups via aliases are relatively simple and elegant, and avoid the need for a more complex namespacing system which would complicate the implementation of `Symbol` etc.

To the specific points

1. Agreed, we have this covered
2. Keywords do seem to be usefully distinct from Symbols, and can serve as enums (this is intentional)
3. There are some use cases where this might be useful, e.g. having a level of indirection through a delegated alias. It would be harder *not* to support this since and expression can be used as a lookup target, so they nest naturally.

Some documentation on the above has been added in CAD026

Closing because there doesn't appear to be any further action needed, but of course feel free to reopen / file a new issue if that changes
